/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.4.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QLocale>
#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionHarley;
    QAction *actionMiranda;
    QAction *actionMiranda_2;
    QAction *actionSobre;
    QAction *actionManual;
    QAction *actionICE_JPG_TIF;
    QAction *actionTIFs_ICE_JPG;
    QAction *actionValor;
    QAction *actionValor_2;
    QAction *actionEspecificar_2;
    QAction *actionThread;
    QAction *actionThread_2;
    QAction *actionTIFF_KMZ;
    QAction *actionMuda_resolucao;
    QAction *actionAbrir;
    QAction *actionPontos;
    QAction *actionEXIF_XMP;
    QAction *actionCapturar_Pontos;
    QAction *actionGerar_GeoTiff;
    QAction *actionTIFF_JPG;
    QAction *action2_pontos;
    QAction *actionCaminho;
    QAction *action_rea;
    QAction *actionLimpar;
    QAction *actionThumbnail;
    QAction *actionPortugu_s;
    QAction *actionIngl_s;
    QAction *actionPreenche_Pol_gono;
    QAction *actionPreto;
    QAction *actionBranco;
    QAction *actionSair;
    QAction *actionDrone;
    QAction *actionGimbal;
    QAction *actionGDAL;
    QAction *actionInterno;
    QAction *actionBordas_na_imagens_processadas;
    QAction *actionCortarTIFF;
    QAction *actionKMZ_TIFF;
    QAction *actionDesativado;
    QAction *actionOriginais;
    QAction *actionProcessadas;
    QAction *actionRaio_30_pts;
    QAction *actionCarregar;
    QAction *actionUsar;
    QAction *actionMostrar;
    QAction *actionSalvar_TIF_mixado;
    QAction *actionSave_KML;
    QAction *actionLoad_KML;
    QAction *actionEspecificar;
    QAction *actionHarley_3;
    QAction *actionConversor_Coordenadas;
    QAction *actionMover_imagens;
    QAction *actionDesloca_Imagem;
    QAction *actionCoordenadas_Centrais_na_tabela;
    QAction *actionM_dia;
    QAction *actionShow;
    QAction *actionUsar_imagens_do_drone_em_curva;
    QAction *actionTodas_as_imagens;
    QAction *actionSendido_nico_1;
    QAction *actionSentido_unico_2;
    QAction *actionUsar_imagens_da_primeira_e_ltima_linha;
    QAction *actionMostrar_informa_o_dire_es;
    QAction *actionTranspar_ncia;
    QAction *actionMostrar_informa_o_pilha_de_imagens;
    QAction *actionPortugu_s_2;
    QAction *actionIngl_s_2;
    QAction *action1920x1080;
    QAction *action1280x720;
    QWidget *centralWidget;
    QPushButton *btOpenFile;
    QLineEdit *txt_Path;
    QTextBrowser *txt_Output;
    QPushButton *btOpenDirectory;
    QLineEdit *txt_Directory;
    QLineEdit *txt_NumEntries;
    QListWidget *list_Files;
    QLabel *label_Reducao;
    QLineEdit *txt_Reducao;
    QPushButton *bt_Reduzir;
    QPushButton *bt_ProcessarImgs;
    QFrame *line;
    QPushButton *bt_Dir_Proc;
    QLineEdit *txt_Dir_Proc;
    QLineEdit *txt_NumEntries_Proc;
    QPushButton *btCmd;
    QProgressBar *progressBar1;
    QPushButton *bt_Cancelar_Proc;
    QPushButton *bt_Mesclar;
    QLineEdit *txt_Mesclar_Name;
    QPushButton *bt_Lista_Arquivos;
    QLineEdit *txt_Lista_Arquivos;
    QCheckBox *checkBox_GTiff;
    QCheckBox *checkBox_KMZ;
    QCheckBox *checkBox_JPG;
    QPushButton *bt_EXIF_XMP_List;
    QRadioButton *radioButton_Merge;
    QRadioButton *radioButton_Stitch;
    QListWidget *list_Files_Proc;
    QPushButton *bt_Teste;
    QPushButton *bt_DialogPontos;
    QLabel *label_Reducao_2;
    QLineEdit *txt_Escala;
    QLabel *label_Reducao_3;
    QPushButton *bt_limpaProc;
    QLabel *label_Reducao_4;
    QLabel *label_Reducao_5;
    QLabel *label_Reducao_6;
    QLineEdit *txt_Alt_Voo;
    QListWidget *list_Files_Result;
    QLabel *label_Reducao_7;
    QPushButton *bt_MudaResolucao;
    QProgressBar *progressBar_Files;
    QProgressBar *progressBar_Proc;
    QProgressBar *progressBar_Result;
    QPushButton *Limpa_Quadro;
    QTableWidget *tablePontos;
    QCheckBox *checkBox_Linhas;
    QPushButton *pushButton;
    QCheckBox *checkBox_Circle;
    QLineEdit *txt_Dist;
    QCheckBox *CheckBox_Poligono;
    QLineEdit *lineEdit_Area;
    QLabel *label;
    QLabel *label_Perimetro;
    QProgressBar *progressBar_Mesclar;
    QLineEdit *Selected_IMG;
    QLineEdit *Selected_PROC;
    QLineEdit *Selected_RESULT;
    QFrame *line_4;
    QLabel *label_Reducao_8;
    QLineEdit *txt_Nome_Imagem;
    QPushButton *bt_Mostar_Imagem;
    QFrame *line_2;
    QFrame *line_3;
    QPushButton *pushButton_2;
    QMenuBar *menuBar;
    QMenu *menuAlgoritmo;
    QMenu *menuNota_o;
    QMenu *menuCor_NODATA;
    QMenu *menu_ngulo_de_rota_o;
    QMenu *menuMesclagem;
    QMenu *menuMostrar_Coordenadas_Centrais;
    QMenu *menuAltura_de_voo;
    QMenu *menuLingua;
    QMenu *menuResolu_o_2;
    QMenu *menuAjuda;
    QMenu *menuUtilit_rios;
    QMenu *menuMerge_ICE_JPG_Manual;
    QMenu *menuImagem;
    QMenu *menuMadidas;
    QMenu *menuImagem_de_fundo;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->resize(1720, 960);
        MainWindow->setMinimumSize(QSize(1280, 720));
        MainWindow->setMaximumSize(QSize(1720, 960));
        QFont font;
        font.setPointSize(10);
        MainWindow->setFont(font);
        MainWindow->setLocale(QLocale(QLocale::Portuguese, QLocale::Brazil));
        actionHarley = new QAction(MainWindow);
        actionHarley->setObjectName("actionHarley");
        actionMiranda = new QAction(MainWindow);
        actionMiranda->setObjectName("actionMiranda");
        actionMiranda_2 = new QAction(MainWindow);
        actionMiranda_2->setObjectName("actionMiranda_2");
        actionMiranda_2->setCheckable(true);
        actionMiranda_2->setChecked(false);
        actionMiranda_2->setEnabled(false);
        actionMiranda_2->setVisible(true);
        actionSobre = new QAction(MainWindow);
        actionSobre->setObjectName("actionSobre");
        actionSobre->setFont(font);
        actionManual = new QAction(MainWindow);
        actionManual->setObjectName("actionManual");
        actionManual->setFont(font);
        actionICE_JPG_TIF = new QAction(MainWindow);
        actionICE_JPG_TIF->setObjectName("actionICE_JPG_TIF");
        actionTIFs_ICE_JPG = new QAction(MainWindow);
        actionTIFs_ICE_JPG->setObjectName("actionTIFs_ICE_JPG");
        actionTIFs_ICE_JPG->setEnabled(false);
        actionTIFs_ICE_JPG->setVisible(false);
        actionValor = new QAction(MainWindow);
        actionValor->setObjectName("actionValor");
        actionValor->setCheckable(true);
        actionValor->setChecked(true);
        actionValor_2 = new QAction(MainWindow);
        actionValor_2->setObjectName("actionValor_2");
        actionEspecificar_2 = new QAction(MainWindow);
        actionEspecificar_2->setObjectName("actionEspecificar_2");
        actionEspecificar_2->setCheckable(true);
        actionThread = new QAction(MainWindow);
        actionThread->setObjectName("actionThread");
        actionThread->setCheckable(true);
        actionThread->setChecked(true);
        actionThread->setEnabled(false);
        actionThread_2 = new QAction(MainWindow);
        actionThread_2->setObjectName("actionThread_2");
        actionThread_2->setCheckable(true);
        actionThread_2->setChecked(false);
        actionTIFF_KMZ = new QAction(MainWindow);
        actionTIFF_KMZ->setObjectName("actionTIFF_KMZ");
        actionMuda_resolucao = new QAction(MainWindow);
        actionMuda_resolucao->setObjectName("actionMuda_resolucao");
        actionAbrir = new QAction(MainWindow);
        actionAbrir->setObjectName("actionAbrir");
        actionPontos = new QAction(MainWindow);
        actionPontos->setObjectName("actionPontos");
        actionEXIF_XMP = new QAction(MainWindow);
        actionEXIF_XMP->setObjectName("actionEXIF_XMP");
        actionCapturar_Pontos = new QAction(MainWindow);
        actionCapturar_Pontos->setObjectName("actionCapturar_Pontos");
        actionGerar_GeoTiff = new QAction(MainWindow);
        actionGerar_GeoTiff->setObjectName("actionGerar_GeoTiff");
        actionTIFF_JPG = new QAction(MainWindow);
        actionTIFF_JPG->setObjectName("actionTIFF_JPG");
        action2_pontos = new QAction(MainWindow);
        action2_pontos->setObjectName("action2_pontos");
        actionCaminho = new QAction(MainWindow);
        actionCaminho->setObjectName("actionCaminho");
        action_rea = new QAction(MainWindow);
        action_rea->setObjectName("action_rea");
        actionLimpar = new QAction(MainWindow);
        actionLimpar->setObjectName("actionLimpar");
        actionThumbnail = new QAction(MainWindow);
        actionThumbnail->setObjectName("actionThumbnail");
        actionThumbnail->setCheckable(true);
        actionThumbnail->setChecked(true);
        actionPortugu_s = new QAction(MainWindow);
        actionPortugu_s->setObjectName("actionPortugu_s");
        actionPortugu_s->setCheckable(true);
        actionPortugu_s->setChecked(true);
        actionIngl_s = new QAction(MainWindow);
        actionIngl_s->setObjectName("actionIngl_s");
        actionIngl_s->setCheckable(true);
        actionPreenche_Pol_gono = new QAction(MainWindow);
        actionPreenche_Pol_gono->setObjectName("actionPreenche_Pol_gono");
        actionPreenche_Pol_gono->setCheckable(true);
        actionPreenche_Pol_gono->setChecked(true);
        actionPreto = new QAction(MainWindow);
        actionPreto->setObjectName("actionPreto");
        actionPreto->setCheckable(true);
        actionPreto->setChecked(false);
        actionBranco = new QAction(MainWindow);
        actionBranco->setObjectName("actionBranco");
        actionBranco->setCheckable(true);
        actionBranco->setChecked(true);
        actionSair = new QAction(MainWindow);
        actionSair->setObjectName("actionSair");
        actionSair->setFont(font);
        actionDrone = new QAction(MainWindow);
        actionDrone->setObjectName("actionDrone");
        actionDrone->setCheckable(true);
        actionDrone->setChecked(true);
        actionGimbal = new QAction(MainWindow);
        actionGimbal->setObjectName("actionGimbal");
        actionGimbal->setCheckable(true);
        actionGDAL = new QAction(MainWindow);
        actionGDAL->setObjectName("actionGDAL");
        actionGDAL->setCheckable(true);
        actionInterno = new QAction(MainWindow);
        actionInterno->setObjectName("actionInterno");
        actionInterno->setCheckable(true);
        actionInterno->setChecked(true);
        actionBordas_na_imagens_processadas = new QAction(MainWindow);
        actionBordas_na_imagens_processadas->setObjectName("actionBordas_na_imagens_processadas");
        actionBordas_na_imagens_processadas->setCheckable(true);
        actionCortarTIFF = new QAction(MainWindow);
        actionCortarTIFF->setObjectName("actionCortarTIFF");
        actionCortarTIFF->setEnabled(true);
        actionKMZ_TIFF = new QAction(MainWindow);
        actionKMZ_TIFF->setObjectName("actionKMZ_TIFF");
        actionDesativado = new QAction(MainWindow);
        actionDesativado->setObjectName("actionDesativado");
        actionDesativado->setCheckable(true);
        actionDesativado->setChecked(true);
        actionOriginais = new QAction(MainWindow);
        actionOriginais->setObjectName("actionOriginais");
        actionOriginais->setCheckable(true);
        actionProcessadas = new QAction(MainWindow);
        actionProcessadas->setObjectName("actionProcessadas");
        actionProcessadas->setCheckable(true);
        actionRaio_30_pts = new QAction(MainWindow);
        actionRaio_30_pts->setObjectName("actionRaio_30_pts");
        actionCarregar = new QAction(MainWindow);
        actionCarregar->setObjectName("actionCarregar");
        actionUsar = new QAction(MainWindow);
        actionUsar->setObjectName("actionUsar");
        actionUsar->setCheckable(true);
        actionMostrar = new QAction(MainWindow);
        actionMostrar->setObjectName("actionMostrar");
        actionMostrar->setEnabled(false);
        actionSalvar_TIF_mixado = new QAction(MainWindow);
        actionSalvar_TIF_mixado->setObjectName("actionSalvar_TIF_mixado");
        actionSalvar_TIF_mixado->setEnabled(false);
        actionSave_KML = new QAction(MainWindow);
        actionSave_KML->setObjectName("actionSave_KML");
        actionLoad_KML = new QAction(MainWindow);
        actionLoad_KML->setObjectName("actionLoad_KML");
        actionEspecificar = new QAction(MainWindow);
        actionEspecificar->setObjectName("actionEspecificar");
        actionHarley_3 = new QAction(MainWindow);
        actionHarley_3->setObjectName("actionHarley_3");
        actionHarley_3->setEnabled(false);
        actionConversor_Coordenadas = new QAction(MainWindow);
        actionConversor_Coordenadas->setObjectName("actionConversor_Coordenadas");
        actionMover_imagens = new QAction(MainWindow);
        actionMover_imagens->setObjectName("actionMover_imagens");
        actionMover_imagens->setCheckable(true);
        actionMover_imagens->setChecked(true);
        actionDesloca_Imagem = new QAction(MainWindow);
        actionDesloca_Imagem->setObjectName("actionDesloca_Imagem");
        actionCoordenadas_Centrais_na_tabela = new QAction(MainWindow);
        actionCoordenadas_Centrais_na_tabela->setObjectName("actionCoordenadas_Centrais_na_tabela");
        actionCoordenadas_Centrais_na_tabela->setCheckable(true);
        actionM_dia = new QAction(MainWindow);
        actionM_dia->setObjectName("actionM_dia");
        actionM_dia->setCheckable(true);
        actionM_dia->setChecked(true);
        actionShow = new QAction(MainWindow);
        actionShow->setObjectName("actionShow");
        actionShow->setCheckable(true);
        actionShow->setChecked(true);
        actionUsar_imagens_do_drone_em_curva = new QAction(MainWindow);
        actionUsar_imagens_do_drone_em_curva->setObjectName("actionUsar_imagens_do_drone_em_curva");
        actionUsar_imagens_do_drone_em_curva->setCheckable(true);
        actionUsar_imagens_do_drone_em_curva->setChecked(false);
        actionTodas_as_imagens = new QAction(MainWindow);
        actionTodas_as_imagens->setObjectName("actionTodas_as_imagens");
        actionTodas_as_imagens->setCheckable(true);
        actionTodas_as_imagens->setChecked(true);
        actionSendido_nico_1 = new QAction(MainWindow);
        actionSendido_nico_1->setObjectName("actionSendido_nico_1");
        actionSendido_nico_1->setCheckable(true);
        actionSentido_unico_2 = new QAction(MainWindow);
        actionSentido_unico_2->setObjectName("actionSentido_unico_2");
        actionSentido_unico_2->setCheckable(true);
        actionUsar_imagens_da_primeira_e_ltima_linha = new QAction(MainWindow);
        actionUsar_imagens_da_primeira_e_ltima_linha->setObjectName("actionUsar_imagens_da_primeira_e_ltima_linha");
        actionUsar_imagens_da_primeira_e_ltima_linha->setCheckable(true);
        actionUsar_imagens_da_primeira_e_ltima_linha->setChecked(true);
        actionUsar_imagens_da_primeira_e_ltima_linha->setEnabled(true);
        actionUsar_imagens_da_primeira_e_ltima_linha->setVisible(true);
        actionMostrar_informa_o_dire_es = new QAction(MainWindow);
        actionMostrar_informa_o_dire_es->setObjectName("actionMostrar_informa_o_dire_es");
        actionTranspar_ncia = new QAction(MainWindow);
        actionTranspar_ncia->setObjectName("actionTranspar_ncia");
        actionTranspar_ncia->setCheckable(true);
        actionMostrar_informa_o_pilha_de_imagens = new QAction(MainWindow);
        actionMostrar_informa_o_pilha_de_imagens->setObjectName("actionMostrar_informa_o_pilha_de_imagens");
        actionPortugu_s_2 = new QAction(MainWindow);
        actionPortugu_s_2->setObjectName("actionPortugu_s_2");
        actionPortugu_s_2->setCheckable(true);
        actionPortugu_s_2->setChecked(true);
        actionIngl_s_2 = new QAction(MainWindow);
        actionIngl_s_2->setObjectName("actionIngl_s_2");
        actionIngl_s_2->setCheckable(true);
        action1920x1080 = new QAction(MainWindow);
        action1920x1080->setObjectName("action1920x1080");
        action1920x1080->setCheckable(true);
        action1920x1080->setChecked(true);
        action1280x720 = new QAction(MainWindow);
        action1280x720->setObjectName("action1280x720");
        action1280x720->setCheckable(true);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName("centralWidget");
        btOpenFile = new QPushButton(centralWidget);
        btOpenFile->setObjectName("btOpenFile");
        btOpenFile->setEnabled(false);
        btOpenFile->setGeometry(QRect(660, 260, 51, 28));
        QFont font1;
        font1.setFamilies({QString::fromUtf8("Arial")});
        font1.setPointSize(10);
        btOpenFile->setFont(font1);
        txt_Path = new QLineEdit(centralWidget);
        txt_Path->setObjectName("txt_Path");
        txt_Path->setEnabled(true);
        txt_Path->setGeometry(QRect(20, 870, 941, 25));
        txt_Path->setFont(font1);
        txt_Path->setReadOnly(true);
        txt_Output = new QTextBrowser(centralWidget);
        txt_Output->setObjectName("txt_Output");
        txt_Output->setEnabled(true);
        txt_Output->setGeometry(QRect(980, 30, 721, 491));
        txt_Output->setFont(font1);
        txt_Output->setMouseTracking(false);
        txt_Output->setFocusPolicy(Qt::ClickFocus);
        btOpenDirectory = new QPushButton(centralWidget);
        btOpenDirectory->setObjectName("btOpenDirectory");
        btOpenDirectory->setGeometry(QRect(10, 5, 141, 25));
        btOpenDirectory->setFont(font1);
        txt_Directory = new QLineEdit(centralWidget);
        txt_Directory->setObjectName("txt_Directory");
        txt_Directory->setGeometry(QRect(160, 5, 571, 25));
        txt_Directory->setFont(font1);
        txt_Directory->setReadOnly(true);
        txt_NumEntries = new QLineEdit(centralWidget);
        txt_NumEntries->setObjectName("txt_NumEntries");
        txt_NumEntries->setGeometry(QRect(760, 5, 141, 25));
        txt_NumEntries->setFont(font1);
        txt_NumEntries->setLayoutDirection(Qt::LeftToRight);
        txt_NumEntries->setReadOnly(true);
        list_Files = new QListWidget(centralWidget);
        list_Files->setObjectName("list_Files");
        list_Files->setGeometry(QRect(20, 330, 301, 531));
        list_Files->setFont(font1);
        list_Files->setResizeMode(QListView::Adjust);
        list_Files->setViewMode(QListView::ListMode);
        label_Reducao = new QLabel(centralWidget);
        label_Reducao->setObjectName("label_Reducao");
        label_Reducao->setGeometry(QRect(20, 35, 81, 25));
        label_Reducao->setFont(font1);
        txt_Reducao = new QLineEdit(centralWidget);
        txt_Reducao->setObjectName("txt_Reducao");
        txt_Reducao->setGeometry(QRect(100, 35, 41, 25));
        txt_Reducao->setFont(font1);
        bt_Reduzir = new QPushButton(centralWidget);
        bt_Reduzir->setObjectName("bt_Reduzir");
        bt_Reduzir->setGeometry(QRect(210, 35, 171, 25));
        bt_Reduzir->setFont(font1);
        bt_ProcessarImgs = new QPushButton(centralWidget);
        bt_ProcessarImgs->setObjectName("bt_ProcessarImgs");
        bt_ProcessarImgs->setGeometry(QRect(170, 120, 161, 25));
        QFont font2;
        font2.setFamilies({QString::fromUtf8("Arial")});
        font2.setPointSize(10);
        font2.setBold(false);
        bt_ProcessarImgs->setFont(font2);
        line = new QFrame(centralWidget);
        line->setObjectName("line");
        line->setGeometry(QRect(130, 55, 671, 31));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        bt_Dir_Proc = new QPushButton(centralWidget);
        bt_Dir_Proc->setObjectName("bt_Dir_Proc");
        bt_Dir_Proc->setGeometry(QRect(10, 80, 191, 25));
        bt_Dir_Proc->setFont(font1);
        txt_Dir_Proc = new QLineEdit(centralWidget);
        txt_Dir_Proc->setObjectName("txt_Dir_Proc");
        txt_Dir_Proc->setGeometry(QRect(210, 80, 521, 25));
        txt_Dir_Proc->setFont(font1);
        txt_Dir_Proc->setReadOnly(true);
        txt_NumEntries_Proc = new QLineEdit(centralWidget);
        txt_NumEntries_Proc->setObjectName("txt_NumEntries_Proc");
        txt_NumEntries_Proc->setGeometry(QRect(760, 80, 141, 25));
        txt_NumEntries_Proc->setFont(font1);
        txt_NumEntries_Proc->setReadOnly(true);
        btCmd = new QPushButton(centralWidget);
        btCmd->setObjectName("btCmd");
        btCmd->setGeometry(QRect(1640, 840, 61, 23));
        btCmd->setFont(font1);
        progressBar1 = new QProgressBar(centralWidget);
        progressBar1->setObjectName("progressBar1");
        progressBar1->setEnabled(true);
        progressBar1->setGeometry(QRect(1460, 550, 241, 25));
        progressBar1->setFont(font1);
        progressBar1->setValue(24);
        bt_Cancelar_Proc = new QPushButton(centralWidget);
        bt_Cancelar_Proc->setObjectName("bt_Cancelar_Proc");
        bt_Cancelar_Proc->setGeometry(QRect(350, 120, 211, 25));
        bt_Cancelar_Proc->setFont(font1);
        bt_Mesclar = new QPushButton(centralWidget);
        bt_Mesclar->setObjectName("bt_Mesclar");
        bt_Mesclar->setGeometry(QRect(660, 120, 141, 25));
        bt_Mesclar->setFont(font1);
        txt_Mesclar_Name = new QLineEdit(centralWidget);
        txt_Mesclar_Name->setObjectName("txt_Mesclar_Name");
        txt_Mesclar_Name->setGeometry(QRect(1020, 620, 41, 25));
        txt_Mesclar_Name->setFont(font1);
        txt_Mesclar_Name->setReadOnly(true);
        bt_Lista_Arquivos = new QPushButton(centralWidget);
        bt_Lista_Arquivos->setObjectName("bt_Lista_Arquivos");
        bt_Lista_Arquivos->setGeometry(QRect(940, 560, 141, 28));
        bt_Lista_Arquivos->setFont(font1);
        txt_Lista_Arquivos = new QLineEdit(centralWidget);
        txt_Lista_Arquivos->setObjectName("txt_Lista_Arquivos");
        txt_Lista_Arquivos->setGeometry(QRect(940, 710, 111, 25));
        txt_Lista_Arquivos->setFont(font1);
        checkBox_GTiff = new QCheckBox(centralWidget);
        checkBox_GTiff->setObjectName("checkBox_GTiff");
        checkBox_GTiff->setGeometry(QRect(940, 620, 81, 17));
        checkBox_GTiff->setFont(font1);
        checkBox_KMZ = new QCheckBox(centralWidget);
        checkBox_KMZ->setObjectName("checkBox_KMZ");
        checkBox_KMZ->setGeometry(QRect(940, 640, 70, 17));
        checkBox_KMZ->setFont(font1);
        checkBox_JPG = new QCheckBox(centralWidget);
        checkBox_JPG->setObjectName("checkBox_JPG");
        checkBox_JPG->setGeometry(QRect(940, 660, 70, 17));
        checkBox_JPG->setFont(font1);
        bt_EXIF_XMP_List = new QPushButton(centralWidget);
        bt_EXIF_XMP_List->setObjectName("bt_EXIF_XMP_List");
        bt_EXIF_XMP_List->setGeometry(QRect(880, 260, 93, 28));
        radioButton_Merge = new QRadioButton(centralWidget);
        radioButton_Merge->setObjectName("radioButton_Merge");
        radioButton_Merge->setGeometry(QRect(950, 760, 111, 20));
        radioButton_Stitch = new QRadioButton(centralWidget);
        radioButton_Stitch->setObjectName("radioButton_Stitch");
        radioButton_Stitch->setGeometry(QRect(950, 740, 97, 20));
        list_Files_Proc = new QListWidget(centralWidget);
        list_Files_Proc->setObjectName("list_Files_Proc");
        list_Files_Proc->setGeometry(QRect(340, 330, 301, 531));
        list_Files_Proc->setFont(font1);
        list_Files_Proc->setSelectionMode(QAbstractItemView::MultiSelection);
        bt_Teste = new QPushButton(centralWidget);
        bt_Teste->setObjectName("bt_Teste");
        bt_Teste->setEnabled(false);
        bt_Teste->setGeometry(QRect(600, 260, 51, 28));
        bt_DialogPontos = new QPushButton(centralWidget);
        bt_DialogPontos->setObjectName("bt_DialogPontos");
        bt_DialogPontos->setGeometry(QRect(960, 780, 93, 28));
        label_Reducao_2 = new QLabel(centralWidget);
        label_Reducao_2->setObjectName("label_Reducao_2");
        label_Reducao_2->setGeometry(QRect(20, 120, 81, 25));
        label_Reducao_2->setFont(font1);
        txt_Escala = new QLineEdit(centralWidget);
        txt_Escala->setObjectName("txt_Escala");
        txt_Escala->setGeometry(QRect(70, 120, 41, 25));
        label_Reducao_3 = new QLabel(centralWidget);
        label_Reducao_3->setObjectName("label_Reducao_3");
        label_Reducao_3->setGeometry(QRect(120, 120, 21, 25));
        QFont font3;
        font3.setFamilies({QString::fromUtf8("Arial")});
        font3.setPointSize(12);
        label_Reducao_3->setFont(font3);
        bt_limpaProc = new QPushButton(centralWidget);
        bt_limpaProc->setObjectName("bt_limpaProc");
        bt_limpaProc->setGeometry(QRect(410, 260, 141, 28));
        label_Reducao_4 = new QLabel(centralWidget);
        label_Reducao_4->setObjectName("label_Reducao_4");
        label_Reducao_4->setGeometry(QRect(140, 300, 81, 21));
        label_Reducao_4->setFont(font1);
        label_Reducao_5 = new QLabel(centralWidget);
        label_Reducao_5->setObjectName("label_Reducao_5");
        label_Reducao_5->setGeometry(QRect(440, 300, 111, 21));
        label_Reducao_5->setFont(font1);
        label_Reducao_6 = new QLabel(centralWidget);
        label_Reducao_6->setObjectName("label_Reducao_6");
        label_Reducao_6->setGeometry(QRect(20, 260, 101, 21));
        label_Reducao_6->setFont(font1);
        txt_Alt_Voo = new QLineEdit(centralWidget);
        txt_Alt_Voo->setObjectName("txt_Alt_Voo");
        txt_Alt_Voo->setGeometry(QRect(120, 260, 113, 20));
        txt_Alt_Voo->setReadOnly(true);
        list_Files_Result = new QListWidget(centralWidget);
        list_Files_Result->setObjectName("list_Files_Result");
        list_Files_Result->setGeometry(QRect(660, 330, 301, 531));
        label_Reducao_7 = new QLabel(centralWidget);
        label_Reducao_7->setObjectName("label_Reducao_7");
        label_Reducao_7->setGeometry(QRect(770, 300, 111, 21));
        label_Reducao_7->setFont(font1);
        bt_MudaResolucao = new QPushButton(centralWidget);
        bt_MudaResolucao->setObjectName("bt_MudaResolucao");
        bt_MudaResolucao->setGeometry(QRect(970, 700, 81, 31));
        progressBar_Files = new QProgressBar(centralWidget);
        progressBar_Files->setObjectName("progressBar_Files");
        progressBar_Files->setGeometry(QRect(20, 870, 311, 23));
        progressBar_Files->setValue(24);
        progressBar_Proc = new QProgressBar(centralWidget);
        progressBar_Proc->setObjectName("progressBar_Proc");
        progressBar_Proc->setGeometry(QRect(340, 870, 311, 23));
        progressBar_Proc->setValue(24);
        progressBar_Result = new QProgressBar(centralWidget);
        progressBar_Result->setObjectName("progressBar_Result");
        progressBar_Result->setGeometry(QRect(660, 870, 311, 23));
        progressBar_Result->setValue(24);
        Limpa_Quadro = new QPushButton(centralWidget);
        Limpa_Quadro->setObjectName("Limpa_Quadro");
        Limpa_Quadro->setGeometry(QRect(1280, 5, 121, 23));
        tablePontos = new QTableWidget(centralWidget);
        tablePontos->setObjectName("tablePontos");
        tablePontos->setGeometry(QRect(1070, 560, 551, 311));
        checkBox_Linhas = new QCheckBox(centralWidget);
        checkBox_Linhas->setObjectName("checkBox_Linhas");
        checkBox_Linhas->setGeometry(QRect(1630, 640, 70, 18));
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName("pushButton");
        pushButton->setGeometry(QRect(1300, 530, 111, 23));
        checkBox_Circle = new QCheckBox(centralWidget);
        checkBox_Circle->setObjectName("checkBox_Circle");
        checkBox_Circle->setGeometry(QRect(1630, 670, 70, 18));
        checkBox_Circle->setChecked(true);
        txt_Dist = new QLineEdit(centralWidget);
        txt_Dist->setObjectName("txt_Dist");
        txt_Dist->setGeometry(QRect(1510, 880, 111, 20));
        txt_Dist->setReadOnly(true);
        CheckBox_Poligono = new QCheckBox(centralWidget);
        CheckBox_Poligono->setObjectName("CheckBox_Poligono");
        CheckBox_Poligono->setGeometry(QRect(1630, 740, 70, 18));
        lineEdit_Area = new QLineEdit(centralWidget);
        lineEdit_Area->setObjectName("lineEdit_Area");
        lineEdit_Area->setGeometry(QRect(1110, 880, 113, 20));
        lineEdit_Area->setReadOnly(true);
        label = new QLabel(centralWidget);
        label->setObjectName("label");
        label->setGeometry(QRect(1070, 880, 47, 14));
        label->setFont(font1);
        label_Perimetro = new QLabel(centralWidget);
        label_Perimetro->setObjectName("label_Perimetro");
        label_Perimetro->setGeometry(QRect(1435, 880, 71, 16));
        label_Perimetro->setFont(font1);
        progressBar_Mesclar = new QProgressBar(centralWidget);
        progressBar_Mesclar->setObjectName("progressBar_Mesclar");
        progressBar_Mesclar->setGeometry(QRect(240, 170, 481, 25));
        progressBar_Mesclar->setValue(24);
        Selected_IMG = new QLineEdit(centralWidget);
        Selected_IMG->setObjectName("Selected_IMG");
        Selected_IMG->setGeometry(QRect(250, 300, 71, 20));
        Selected_PROC = new QLineEdit(centralWidget);
        Selected_PROC->setObjectName("Selected_PROC");
        Selected_PROC->setGeometry(QRect(570, 300, 71, 20));
        Selected_RESULT = new QLineEdit(centralWidget);
        Selected_RESULT->setObjectName("Selected_RESULT");
        Selected_RESULT->setGeometry(QRect(890, 300, 71, 20));
        line_4 = new QFrame(centralWidget);
        line_4->setObjectName("line_4");
        line_4->setGeometry(QRect(10, 192, 951, 31));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        label_Reducao_8 = new QLabel(centralWidget);
        label_Reducao_8->setObjectName("label_Reducao_8");
        label_Reducao_8->setGeometry(QRect(20, 220, 81, 21));
        label_Reducao_8->setFont(font1);
        txt_Nome_Imagem = new QLineEdit(centralWidget);
        txt_Nome_Imagem->setObjectName("txt_Nome_Imagem");
        txt_Nome_Imagem->setGeometry(QRect(100, 219, 641, 25));
        txt_Nome_Imagem->setFont(font1);
        txt_Nome_Imagem->setReadOnly(true);
        bt_Mostar_Imagem = new QPushButton(centralWidget);
        bt_Mostar_Imagem->setObjectName("bt_Mostar_Imagem");
        bt_Mostar_Imagem->setGeometry(QRect(770, 219, 111, 28));
        bt_Mostar_Imagem->setFont(font1);
        line_2 = new QFrame(centralWidget);
        line_2->setObjectName("line_2");
        line_2->setGeometry(QRect(130, 140, 671, 31));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(centralWidget);
        line_3->setObjectName("line_3");
        line_3->setGeometry(QRect(130, 240, 671, 31));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        pushButton_2 = new QPushButton(centralWidget);
        pushButton_2->setObjectName("pushButton_2");
        pushButton_2->setGeometry(QRect(750, 260, 75, 24));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName("menuBar");
        menuBar->setGeometry(QRect(0, 0, 1720, 24));
        menuAlgoritmo = new QMenu(menuBar);
        menuAlgoritmo->setObjectName("menuAlgoritmo");
        menuNota_o = new QMenu(menuAlgoritmo);
        menuNota_o->setObjectName("menuNota_o");
        menuCor_NODATA = new QMenu(menuAlgoritmo);
        menuCor_NODATA->setObjectName("menuCor_NODATA");
        menu_ngulo_de_rota_o = new QMenu(menuAlgoritmo);
        menu_ngulo_de_rota_o->setObjectName("menu_ngulo_de_rota_o");
        menuMesclagem = new QMenu(menuAlgoritmo);
        menuMesclagem->setObjectName("menuMesclagem");
        menuMostrar_Coordenadas_Centrais = new QMenu(menuAlgoritmo);
        menuMostrar_Coordenadas_Centrais->setObjectName("menuMostrar_Coordenadas_Centrais");
        menuAltura_de_voo = new QMenu(menuAlgoritmo);
        menuAltura_de_voo->setObjectName("menuAltura_de_voo");
        menuLingua = new QMenu(menuAlgoritmo);
        menuLingua->setObjectName("menuLingua");
        menuResolu_o_2 = new QMenu(menuAlgoritmo);
        menuResolu_o_2->setObjectName("menuResolu_o_2");
        menuAjuda = new QMenu(menuBar);
        menuAjuda->setObjectName("menuAjuda");
        menuUtilit_rios = new QMenu(menuBar);
        menuUtilit_rios->setObjectName("menuUtilit_rios");
        menuMerge_ICE_JPG_Manual = new QMenu(menuUtilit_rios);
        menuMerge_ICE_JPG_Manual->setObjectName("menuMerge_ICE_JPG_Manual");
        menuImagem = new QMenu(menuBar);
        menuImagem->setObjectName("menuImagem");
        menuMadidas = new QMenu(menuImagem);
        menuMadidas->setObjectName("menuMadidas");
        menuImagem_de_fundo = new QMenu(menuImagem);
        menuImagem_de_fundo->setObjectName("menuImagem_de_fundo");
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName("mainToolBar");
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName("statusBar");
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menuAjuda->menuAction());
        menuBar->addAction(menuImagem->menuAction());
        menuBar->addAction(menuUtilit_rios->menuAction());
        menuBar->addAction(menuAlgoritmo->menuAction());
        menuAlgoritmo->addAction(menuLingua->menuAction());
        menuAlgoritmo->addSeparator();
        menuAlgoritmo->addAction(menu_ngulo_de_rota_o->menuAction());
        menuAlgoritmo->addSeparator();
        menuAlgoritmo->addAction(menuCor_NODATA->menuAction());
        menuAlgoritmo->addSeparator();
        menuAlgoritmo->addAction(menuMesclagem->menuAction());
        menuAlgoritmo->addAction(actionTranspar_ncia);
        menuAlgoritmo->addSeparator();
        menuAlgoritmo->addAction(actionPreenche_Pol_gono);
        menuAlgoritmo->addSeparator();
        menuAlgoritmo->addAction(menuNota_o->menuAction());
        menuAlgoritmo->addSeparator();
        menuAlgoritmo->addAction(actionThread_2);
        menuAlgoritmo->addSeparator();
        menuAlgoritmo->addAction(actionThumbnail);
        menuAlgoritmo->addSeparator();
        menuAlgoritmo->addAction(actionBordas_na_imagens_processadas);
        menuAlgoritmo->addSeparator();
        menuAlgoritmo->addAction(menuMostrar_Coordenadas_Centrais->menuAction());
        menuAlgoritmo->addAction(actionCoordenadas_Centrais_na_tabela);
        menuAlgoritmo->addSeparator();
        menuAlgoritmo->addAction(menuAltura_de_voo->menuAction());
        menuAlgoritmo->addSeparator();
        menuAlgoritmo->addAction(actionMover_imagens);
        menuAlgoritmo->addSeparator();
        menuAlgoritmo->addAction(menuResolu_o_2->menuAction());
        menuAlgoritmo->addAction(actionMiranda_2);
        menuAlgoritmo->addAction(actionHarley_3);
        menuAlgoritmo->addSeparator();
        menuNota_o->addAction(actionPortugu_s);
        menuNota_o->addAction(actionIngl_s);
        menuCor_NODATA->addAction(actionPreto);
        menuCor_NODATA->addAction(actionBranco);
        menu_ngulo_de_rota_o->addAction(actionDrone);
        menu_ngulo_de_rota_o->addAction(actionGimbal);
        menu_ngulo_de_rota_o->addSeparator();
        menu_ngulo_de_rota_o->addAction(actionM_dia);
        menu_ngulo_de_rota_o->addSeparator();
        menu_ngulo_de_rota_o->addAction(actionShow);
        menuMesclagem->addAction(actionGDAL);
        menuMesclagem->addAction(actionInterno);
        menuMesclagem->addSeparator();
        menuMesclagem->addAction(actionTodas_as_imagens);
        menuMesclagem->addAction(actionSendido_nico_1);
        menuMesclagem->addAction(actionSentido_unico_2);
        menuMesclagem->addAction(actionUsar_imagens_da_primeira_e_ltima_linha);
        menuMesclagem->addSeparator();
        menuMesclagem->addAction(actionUsar_imagens_do_drone_em_curva);
        menuMostrar_Coordenadas_Centrais->addAction(actionDesativado);
        menuMostrar_Coordenadas_Centrais->addAction(actionOriginais);
        menuMostrar_Coordenadas_Centrais->addAction(actionProcessadas);
        menuMostrar_Coordenadas_Centrais->addSeparator();
        menuMostrar_Coordenadas_Centrais->addAction(actionRaio_30_pts);
        menuAltura_de_voo->addAction(actionEspecificar_2);
        menuAltura_de_voo->addAction(actionValor);
        menuLingua->addAction(actionPortugu_s_2);
        menuLingua->addAction(actionIngl_s_2);
        menuResolu_o_2->addAction(action1920x1080);
        menuResolu_o_2->addAction(action1280x720);
        menuAjuda->addAction(actionSobre);
        menuAjuda->addAction(actionManual);
        menuAjuda->addSeparator();
        menuAjuda->addAction(actionSair);
        menuUtilit_rios->addSeparator();
        menuUtilit_rios->addSeparator();
        menuUtilit_rios->addAction(actionICE_JPG_TIF);
        menuUtilit_rios->addAction(menuMerge_ICE_JPG_Manual->menuAction());
        menuUtilit_rios->addAction(actionTIFs_ICE_JPG);
        menuUtilit_rios->addSeparator();
        menuUtilit_rios->addAction(actionConversor_Coordenadas);
        menuUtilit_rios->addSeparator();
        menuUtilit_rios->addAction(actionDesloca_Imagem);
        menuMerge_ICE_JPG_Manual->addAction(actionCapturar_Pontos);
        menuMerge_ICE_JPG_Manual->addAction(actionGerar_GeoTiff);
        menuImagem->addAction(actionAbrir);
        menuImagem->addAction(actionSalvar_TIF_mixado);
        menuImagem->addSeparator();
        menuImagem->addAction(menuImagem_de_fundo->menuAction());
        menuImagem->addSeparator();
        menuImagem->addAction(actionMuda_resolucao);
        menuImagem->addSeparator();
        menuImagem->addAction(actionTIFF_KMZ);
        menuImagem->addAction(actionTIFF_JPG);
        menuImagem->addAction(actionKMZ_TIFF);
        menuImagem->addSeparator();
        menuImagem->addAction(actionPontos);
        menuImagem->addSeparator();
        menuImagem->addAction(actionEXIF_XMP);
        menuImagem->addSeparator();
        menuImagem->addAction(actionMostrar_informa_o_dire_es);
        menuImagem->addAction(actionMostrar_informa_o_pilha_de_imagens);
        menuImagem->addSeparator();
        menuImagem->addAction(menuMadidas->menuAction());
        menuImagem->addSeparator();
        menuImagem->addAction(actionCortarTIFF);
        menuImagem->addSeparator();
        menuImagem->addAction(actionSave_KML);
        menuImagem->addAction(actionLoad_KML);
        menuMadidas->addAction(actionCaminho);
        menuMadidas->addAction(action_rea);
        menuMadidas->addAction(actionLimpar);
        menuImagem_de_fundo->addAction(actionCarregar);
        menuImagem_de_fundo->addAction(actionUsar);
        menuImagem_de_fundo->addAction(actionMostrar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "Geo", nullptr));
        actionHarley->setText(QCoreApplication::translate("MainWindow", "Harley", nullptr));
        actionMiranda->setText(QCoreApplication::translate("MainWindow", "Miranda", nullptr));
        actionMiranda_2->setText(QCoreApplication::translate("MainWindow", "Miranda", nullptr));
        actionSobre->setText(QCoreApplication::translate("MainWindow", "Sobre", nullptr));
        actionManual->setText(QCoreApplication::translate("MainWindow", "Manual", nullptr));
        actionICE_JPG_TIF->setText(QCoreApplication::translate("MainWindow", "JPG -> GeoTIFF (auto)", nullptr));
        actionTIFs_ICE_JPG->setText(QCoreApplication::translate("MainWindow", "TIFs -> ICE(JPG)", nullptr));
        actionValor->setText(QCoreApplication::translate("MainWindow", "Valor: 30 m", nullptr));
        actionValor_2->setText(QCoreApplication::translate("MainWindow", "Valor", nullptr));
        actionEspecificar_2->setText(QCoreApplication::translate("MainWindow", "Especificar", nullptr));
        actionThread->setText(QCoreApplication::translate("MainWindow", "Th", nullptr));
        actionThread_2->setText(QCoreApplication::translate("MainWindow", "Thread", nullptr));
        actionTIFF_KMZ->setText(QCoreApplication::translate("MainWindow", "TIFF -> KMZ", nullptr));
        actionMuda_resolucao->setText(QCoreApplication::translate("MainWindow", "Muda resolu\303\247\303\243o", nullptr));
        actionAbrir->setText(QCoreApplication::translate("MainWindow", "Abrir", nullptr));
        actionPontos->setText(QCoreApplication::translate("MainWindow", "Pontos", nullptr));
        actionEXIF_XMP->setText(QCoreApplication::translate("MainWindow", "EXIF-XMP", nullptr));
        actionCapturar_Pontos->setText(QCoreApplication::translate("MainWindow", "Capturar Pontos", nullptr));
        actionGerar_GeoTiff->setText(QCoreApplication::translate("MainWindow", "Gerar GeoTiff", nullptr));
        actionTIFF_JPG->setText(QCoreApplication::translate("MainWindow", "TIFF -> JPG", nullptr));
        action2_pontos->setText(QCoreApplication::translate("MainWindow", "2 pontos", nullptr));
        actionCaminho->setText(QCoreApplication::translate("MainWindow", "Linear", nullptr));
        action_rea->setText(QCoreApplication::translate("MainWindow", "Poligono", nullptr));
        actionLimpar->setText(QCoreApplication::translate("MainWindow", "Limpar", nullptr));
        actionThumbnail->setText(QCoreApplication::translate("MainWindow", "Thumbnail", nullptr));
        actionPortugu_s->setText(QCoreApplication::translate("MainWindow", "Portugu\303\252s", nullptr));
        actionIngl_s->setText(QCoreApplication::translate("MainWindow", "Ingl\303\252s", nullptr));
        actionPreenche_Pol_gono->setText(QCoreApplication::translate("MainWindow", "Preenche Pol\303\255gono", nullptr));
        actionPreto->setText(QCoreApplication::translate("MainWindow", "Preto", nullptr));
        actionBranco->setText(QCoreApplication::translate("MainWindow", "Branco", nullptr));
        actionSair->setText(QCoreApplication::translate("MainWindow", "Sair", nullptr));
        actionDrone->setText(QCoreApplication::translate("MainWindow", "Drone", nullptr));
        actionGimbal->setText(QCoreApplication::translate("MainWindow", "Gimbal", nullptr));
        actionGDAL->setText(QCoreApplication::translate("MainWindow", "GDAL", nullptr));
        actionInterno->setText(QCoreApplication::translate("MainWindow", "Interno", nullptr));
        actionBordas_na_imagens_processadas->setText(QCoreApplication::translate("MainWindow", "Bordas nas imagens processadas", nullptr));
        actionCortarTIFF->setText(QCoreApplication::translate("MainWindow", "CortarTIFF", nullptr));
        actionKMZ_TIFF->setText(QCoreApplication::translate("MainWindow", "KMZ -> TIFF", nullptr));
        actionDesativado->setText(QCoreApplication::translate("MainWindow", "Desativado", nullptr));
        actionOriginais->setText(QCoreApplication::translate("MainWindow", "Originais", nullptr));
        actionProcessadas->setText(QCoreApplication::translate("MainWindow", "Processadas", nullptr));
        actionRaio_30_pts->setText(QCoreApplication::translate("MainWindow", "Raio: 30 pts", nullptr));
        actionCarregar->setText(QCoreApplication::translate("MainWindow", "Carregar", nullptr));
        actionUsar->setText(QCoreApplication::translate("MainWindow", "Usar", nullptr));
        actionMostrar->setText(QCoreApplication::translate("MainWindow", "Mostrar", nullptr));
        actionSalvar_TIF_mixado->setText(QCoreApplication::translate("MainWindow", "Salvar", nullptr));
        actionSave_KML->setText(QCoreApplication::translate("MainWindow", "Grava KML", nullptr));
        actionLoad_KML->setText(QCoreApplication::translate("MainWindow", "L\303\252 KML/SHP", nullptr));
        actionEspecificar->setText(QCoreApplication::translate("MainWindow", "Especificar", nullptr));
        actionHarley_3->setText(QCoreApplication::translate("MainWindow", "Harley", nullptr));
        actionConversor_Coordenadas->setText(QCoreApplication::translate("MainWindow", "Conversor Coordenadas", nullptr));
        actionMover_imagens->setText(QCoreApplication::translate("MainWindow", "Mover imagens fora do padr\303\243o", nullptr));
        actionDesloca_Imagem->setText(QCoreApplication::translate("MainWindow", "Desloca Imagem", nullptr));
        actionCoordenadas_Centrais_na_tabela->setText(QCoreApplication::translate("MainWindow", "Coordenadas Centrais na tabela", nullptr));
        actionM_dia->setText(QCoreApplication::translate("MainWindow", "M\303\251dia", nullptr));
        actionShow->setText(QCoreApplication::translate("MainWindow", "Show", nullptr));
        actionUsar_imagens_do_drone_em_curva->setText(QCoreApplication::translate("MainWindow", "Usar imagens do drone em curva", nullptr));
        actionTodas_as_imagens->setText(QCoreApplication::translate("MainWindow", "Todas as imagens", nullptr));
        actionSendido_nico_1->setText(QCoreApplication::translate("MainWindow", "Sentido \303\272nico 1", nullptr));
        actionSentido_unico_2->setText(QCoreApplication::translate("MainWindow", "Sentido unico 2", nullptr));
        actionUsar_imagens_da_primeira_e_ltima_linha->setText(QCoreApplication::translate("MainWindow", "Usar imagens da primeira e \303\272ltima linha", nullptr));
        actionMostrar_informa_o_dire_es->setText(QCoreApplication::translate("MainWindow", "Mostrar informa\303\247\303\243o dire\303\247\303\265es", nullptr));
        actionTranspar_ncia->setText(QCoreApplication::translate("MainWindow", "Transpar\303\252ncia", nullptr));
        actionMostrar_informa_o_pilha_de_imagens->setText(QCoreApplication::translate("MainWindow", "Mostrar informa\303\247\303\243o pilha de imagens", nullptr));
        actionPortugu_s_2->setText(QCoreApplication::translate("MainWindow", "Portugu\303\252s", nullptr));
        actionIngl_s_2->setText(QCoreApplication::translate("MainWindow", "Ingl\303\252s", nullptr));
        action1920x1080->setText(QCoreApplication::translate("MainWindow", "1920x1080", nullptr));
        action1280x720->setText(QCoreApplication::translate("MainWindow", "1280x720", nullptr));
        btOpenFile->setText(QCoreApplication::translate("MainWindow", "Teste2", nullptr));
        btOpenDirectory->setText(QCoreApplication::translate("MainWindow", "Diret\303\263rio imagens", nullptr));
        label_Reducao->setText(QCoreApplication::translate("MainWindow", "Redu\303\247\303\243o:", nullptr));
        bt_Reduzir->setText(QCoreApplication::translate("MainWindow", "Reduzir n\302\272 imagens", nullptr));
        bt_ProcessarImgs->setText(QCoreApplication::translate("MainWindow", "Processar imagens", nullptr));
        bt_Dir_Proc->setText(QCoreApplication::translate("MainWindow", "Diret\303\263rio processamento", nullptr));
        btCmd->setText(QCoreApplication::translate("MainWindow", "Janela de Comandos", nullptr));
        bt_Cancelar_Proc->setText(QCoreApplication::translate("MainWindow", "Cancelar Processamento", nullptr));
        bt_Mesclar->setText(QCoreApplication::translate("MainWindow", "Mesclar imagens", nullptr));
        bt_Lista_Arquivos->setText(QCoreApplication::translate("MainWindow", "Lista de arquivos", nullptr));
        checkBox_GTiff->setText(QCoreApplication::translate("MainWindow", "GeoTiff", nullptr));
        checkBox_KMZ->setText(QCoreApplication::translate("MainWindow", "KMZ", nullptr));
        checkBox_JPG->setText(QCoreApplication::translate("MainWindow", "JPG", nullptr));
        bt_EXIF_XMP_List->setText(QCoreApplication::translate("MainWindow", "EXIF-XMP", nullptr));
        radioButton_Merge->setText(QCoreApplication::translate("MainWindow", "Merge", nullptr));
        radioButton_Stitch->setText(QCoreApplication::translate("MainWindow", "Stitch", nullptr));
        bt_Teste->setText(QCoreApplication::translate("MainWindow", "Teste", nullptr));
        bt_DialogPontos->setText(QCoreApplication::translate("MainWindow", "Pontos", nullptr));
        label_Reducao_2->setText(QCoreApplication::translate("MainWindow", "Escala:", nullptr));
        label_Reducao_3->setText(QCoreApplication::translate("MainWindow", "%", nullptr));
        bt_limpaProc->setText(QCoreApplication::translate("MainWindow", "Limpa Diret\303\263rio", nullptr));
        label_Reducao_4->setText(QCoreApplication::translate("MainWindow", "Originais:", nullptr));
        label_Reducao_5->setText(QCoreApplication::translate("MainWindow", "Processados:", nullptr));
        label_Reducao_6->setText(QCoreApplication::translate("MainWindow", "Altura do voo:", nullptr));
        label_Reducao_7->setText(QCoreApplication::translate("MainWindow", "Resultados:", nullptr));
        bt_MudaResolucao->setText(QCoreApplication::translate("MainWindow", "Muda Resolu\303\247\303\243o", nullptr));
        Limpa_Quadro->setText(QCoreApplication::translate("MainWindow", "Limpa Quadro", nullptr));
        checkBox_Linhas->setText(QCoreApplication::translate("MainWindow", "Linhas", nullptr));
        pushButton->setText(QCoreApplication::translate("MainWindow", "Limpa Pontos", nullptr));
        checkBox_Circle->setText(QCoreApplication::translate("MainWindow", "Circulos", nullptr));
        CheckBox_Poligono->setText(QCoreApplication::translate("MainWindow", "Poligono", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "\303\201rea:", nullptr));
        label_Perimetro->setText(QCoreApplication::translate("MainWindow", "Caminho:", nullptr));
        label_Reducao_8->setText(QCoreApplication::translate("MainWindow", "Imagem:", nullptr));
        bt_Mostar_Imagem->setText(QCoreApplication::translate("MainWindow", "Mostrar", nullptr));
        pushButton_2->setText(QCoreApplication::translate("MainWindow", "Teste 3", nullptr));
        menuAlgoritmo->setTitle(QCoreApplication::translate("MainWindow", "Config", nullptr));
        menuNota_o->setTitle(QCoreApplication::translate("MainWindow", "Separa\303\247\303\243o decimal", nullptr));
        menuCor_NODATA->setTitle(QCoreApplication::translate("MainWindow", "Cor NODATA", nullptr));
        menu_ngulo_de_rota_o->setTitle(QCoreApplication::translate("MainWindow", "\303\202ngulo de rota\303\247\303\243o", nullptr));
        menuMesclagem->setTitle(QCoreApplication::translate("MainWindow", "Mesclagem", nullptr));
        menuMostrar_Coordenadas_Centrais->setTitle(QCoreApplication::translate("MainWindow", "Mostrar Coordenadas Centrais", nullptr));
        menuAltura_de_voo->setTitle(QCoreApplication::translate("MainWindow", "Altura de voo", nullptr));
        menuLingua->setTitle(QCoreApplication::translate("MainWindow", "Lingua", nullptr));
        menuResolu_o_2->setTitle(QCoreApplication::translate("MainWindow", "Resolu\303\247\303\243o", nullptr));
        menuAjuda->setTitle(QCoreApplication::translate("MainWindow", "Ajuda", nullptr));
        menuUtilit_rios->setTitle(QCoreApplication::translate("MainWindow", "Utilit\303\241rios", nullptr));
        menuMerge_ICE_JPG_Manual->setTitle(QCoreApplication::translate("MainWindow", "JPG -> GeoTIFF (manual)", nullptr));
        menuImagem->setTitle(QCoreApplication::translate("MainWindow", "Imagem", nullptr));
        menuMadidas->setTitle(QCoreApplication::translate("MainWindow", "Medidas", nullptr));
        menuImagem_de_fundo->setTitle(QCoreApplication::translate("MainWindow", "Imagem de refer\303\252ncia", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
